package org.chatting.client.gui.event;

public enum EventType {
    CHANGE_SCENE,
    LOGIN_BUTTON_CLICK, LOGIN_RESULT_RECEIVED,
    SIGN_UP_BUTTON_CLICK, SIGN_UP_RESULT_RECEIVED,
    SEND_BUTTON_CLICK,
    CHAT_MESSAGE_RECEIVED, USER_LIST_RECEIVED,
    USER_STATISTICS_RECEIVED
}
